
import clouds from './Ads/Clouds.jpg';

export const BLOGPOSTS = [
    {
        slug: "the-little-song-that-wouldnt-stop",
        image: clouds,
        title: "The Little Song That Wouldn't Stop",
        content:
        "Sometimes a tune sneaks up on you — not the kind that blares from speakers, but the small, sticky melody that lives in the corners of your day. I found one of those this morning in the hum of the kettle: three notes, bright and persistent, like a tiny brass band with a caffeine habit. I couldn't help smiling.\nWhat I love about music is how honest it is without trying. A two-chord loop can confess loneliness; a drum fill can throw a party. Today’s loop turned my coffee routine into a film score. For ten minutes I was a protagonist striding down the pavement, even though I was really just late for a meeting.\nIf you want to catch one of these moments, put your phone away for five minutes and listen — not to fill the silence, but to meet it. You might hear a neighbor’s rhythm, the careful tempo of footsteps, or a melody born of a squeaky gate. Music isn’t only for concerts; it’s stitched into the mundane, waiting to be noticed.\nSo, here's to small songs: the elevator hums, the whistle in a bus line, the melody you whistle wrong but keep anyway. They’re proof that soundtrack is a mindset. Today, I learned that a kettle can be a composer — and I’m glad it decided to write me a tiny anthem.",
    },
    { slug: "the-art-of-wearing-what-feels-like-you", image: clouds, title: "The Art of Wearing What Feels Like You", content: "Fashion trends move faster than morning coffee runs — one week it’s quiet luxury, the next it’s neon cowboy boots. But lately, I’ve been thinking that real style isn’t about keeping up; it’s about slowing down long enough to ask, “Do I actually like this?\nThis morning, I threw on an oversized blazer, my favorite worn-in jeans, and sneakers that have definitely seen better days. And honestly? It felt right. Not polished, not perfect — just mine. There’s something powerful about clothing that tells the truth instead of performing it.\nThe best-dressed people I know aren’t necessarily the trendiest. They wear confidence like an accessory — something that doesn’t come from a store. A tucked-in tee, a vintage pin, a bold lipstick — it’s less about the item and more about the intention behind it.\nSo here’s my new rule: if it makes you walk taller, it’s in style. Fashion isn’t a checklist; it’s a conversation with yourself. And today, mine said, “Let’s keep the sneakers.”" },
    { slug: "the-magic-of-watching-the-same-movie-twice", image: clouds, title: "The Magic of Watching the Same Movie Twice", content: "There’s something oddly comforting about rewatching a movie you already know by heart. No plot twists left, no surprises — just the familiar rhythm of lines you could almost recite and scenes that feel like old friends.\nLast night, I watched Before Sunrise again. I knew exactly when Jesse would smirk and when Céline would look away — but somehow, it still felt new. Maybe that’s the trick: the movie doesn’t change, you do. Each time you come back, you bring a different version of yourself to the story.\nMovies are time capsules. They hold not just the world on screen, but the memory of who you were when you first watched them — what you were hoping for, who you were texting, what you were missing.\nSo if you ever feel a little lost, try pressing play on something familiar. Let it remind you where you’ve been, and maybe, quietly, show you where you’re going next." },
    { slug: "learning-to-breathe-between-headlines" , image: clouds, title: "Learning to Breathe Between Headlines", content: "Lately, it feels like the news never sleeps — and neither do our thoughts about it. Every scroll brings a new crisis, a new opinion, a new reason to sigh. It’s exhausting trying to keep up with a world that refreshes faster than we can process.\nBut here’s the thing: information isn’t the same as understanding. I’ve started taking “headline breaks” — moments where I read one story deeply instead of ten quickly. Sometimes I even read an article twice, not for updates, but for perspective. It slows the world down just enough to feel real again.\nThe news matters, of course. It tells us who we are and what we value. But so does the silence after — the part where we think, question, and decide what we’ll do next. Maybe being informed isn’t about knowing everything; maybe it’s about caring intentionally.\nSo today, I’m reading slowly. The world can wait a few minutes." },
    { slug: "the-comfort-of-just-one-more-episode" , image: clouds, title: "The Comfort Of \"Just One More Episode\"", content: "There’s a special kind of comfort in finding your series — the one you keep returning to after a long day. Maybe it’s the familiar theme song, or the way you already know which character’s about to make a bad decision (and love them anyway). It’s not just watching; it’s visiting old friends.\nLately, I’ve been rewatching Parks and Recreation. I don’t even need to pay attention anymore — it just hums in the background, filling the quiet. And somehow, that feels safe. Like life can be paused, rewound, and played again until it makes sense.\nWe live in a world that wants us to binge everything, but sometimes the best way to enjoy a series is to savor it — one episode, one laugh, one moment at a time.\nSo tonight, I’ll hit “next episode” without guilt. Some stories are meant to be lived slowly." },
    { slug: "when-a-song-finds-you", image: clouds, title: "When a Song Finds You", content: "Sometimes you don’t go looking for music — it finds you. Maybe it’s playing faintly from a café speaker, or spilling from a stranger’s headphones on the bus. Just a few notes, and suddenly you’re somewhere else entirely.\nThe right song doesn’t just fill silence; it fills space. It sneaks into the corners of your day, reminding you of something you almost forgot — a person, a feeling, a version of yourself that still hums quietly inside.\nLast week, I stumbled upon a song I hadn’t heard in years. Within seconds, I was back in an old car with the windows down, laughing about nothing in particular. It’s strange how melody travels — like time, but kinder.\nSo if a song finds you, let it stay a while. Don’t rush it, don’t skip it. Just listen. Some moments deserve a soundtrack." },
];
