/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FlexRouteImport } from './routes/flex'
import { Route as IndexRouteImport } from './routes/index'

const FlexRoute = FlexRouteImport.update({
  id: '/flex',
  path: '/flex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flex': typeof FlexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flex': typeof FlexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flex': typeof FlexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/flex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/flex'
  id: '__root__' | '/' | '/flex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlexRoute: typeof FlexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/flex': {
      id: '/flex'
      path: '/flex'
      fullPath: '/flex'
      preLoaderRoute: typeof FlexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlexRoute: FlexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
